spring.application.name=moviewebapp

spring.datasource.url=jdbc:postgresql://localhost:5432/moviewebapp
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=pJZn3cXvycyMPmZ1flAigxKyAkrtAQnvWr6pxZTUG74
jwt.expiration=3600000
jwt.refresh.expiration=86400000

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true